// <auto-generated />
using FishAndChips.Services.CouponAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FishAndChips.Services.CouponAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FishAndChips.Services.DiscountAPI.Models.Coupon", b =>
                {
                    b.Property<int>("CouponID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouponID"));

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DiscountAmount")
                        .HasColumnType("float");

                    b.Property<int>("MinAmount")
                        .HasColumnType("int");

                    b.HasKey("CouponID");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            CouponID = 1,
                            CouponCode = "TestOFF",
                            DiscountAmount = 10.0,
                            MinAmount = 100
                        },
                        new
                        {
                            CouponID = 2,
                            CouponCode = "Save20",
                            DiscountAmount = 20.0,
                            MinAmount = 200
                        },
                        new
                        {
                            CouponID = 3,
                            CouponCode = "HalfPrice",
                            DiscountAmount = 50.0,
                            MinAmount = 500
                        },
                        new
                        {
                            CouponID = 4,
                            CouponCode = "FreeShip",
                            DiscountAmount = 15.0,
                            MinAmount = 150
                        },
                        new
                        {
                            CouponID = 5,
                            CouponCode = "Welcome10",
                            DiscountAmount = 10.0,
                            MinAmount = 50
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
